name = "RDDIP"
uuid = "ca7a9b78-2274-4768-96cb-57c67a9f2eff"
authors = ["MathisAzema <az_mathis@orange.fr>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Distributed = "1.11.0"
Dualization = "0.7.1"
Gurobi = "1.7.6"
HTTP = "1.10.19"
JSON = "1.2.0"
JuMP = "1.29.2"
Logging = "1.11.0"
MutableArithmetics = "1.6.7"
NCDatasets = "0.14.9"
Printf = "1.11.0"
Random = "1.11.0"
RecipesBase = "1.3.4"
Reexport = "1.2.2"
SDDP = "1.13.1"
SHA = "0.7.0"
Statistics = "1.11.1"
Suppressor = "0.2.8"
TimerOutputs = "0.5.29"
XLSX = "0.10.4"
